# -*- coding: utf-8 -*-
"""
================================================================================
 world/calling_codes.py
================================================================================
 Country calling codes (E.164).

 Data only.

 Sections
 --------
 CALLING_CODE_TO_COUNTRY     : calling code -> country name (int key)
 COUNTRY_TO_CALLING_CODE     : country name -> calling code
 NANP_AREA_CODES             : North American Numbering Plan area codes
                               (calling code +1 territory codes)
 INTERNATIONAL_PREFIXES      : international dial-out prefixes by country
================================================================================
"""

# =============================================================================
# CALLING CODE -> COUNTRY
# =============================================================================
# Every unique country-level calling code.
# Note: calling code 1 (NANP) covers US, Canada, and many Caribbean
# territories. The sub-codes are listed separately in NANP_AREA_CODES.

CALLING_CODE_TO_COUNTRY = {
    # Europe
    30:  "Greece",
    31:  "Netherlands",
    32:  "Belgium",
    33:  "France",
    34:  "Spain",
    36:  "Hungary",
    39:  "Italy",
    40:  "Romania",
    41:  "Switzerland",
    43:  "Austria",
    44:  "United Kingdom",
    45:  "Denmark",
    46:  "Sweden",
    47:  "Norway",
    48:  "Poland",
    49:  "Germany",
    350: "Gibraltar",
    351: "Portugal",
    352: "Luxembourg",
    353: "Ireland",
    354: "Iceland",
    355: "Albania",
    356: "Malta",
    357: "Cyprus",
    358: "Finland",
    359: "Bulgaria",
    370: "Lithuania",
    371: "Latvia",
    372: "Estonia",
    373: "Moldova",
    374: "Armenia",
    375: "Belarus",
    376: "Andorra",
    377: "Monaco",
    378: "San Marino",
    379: "Vatican City",
    380: "Ukraine",
    381: "Serbia",
    382: "Montenegro",
    383: "Kosovo",
    385: "Croatia",
    386: "Slovenia",
    387: "Bosnia and Herzegovina",
    389: "North Macedonia",
    420: "Czech Republic",
    421: "Slovakia",
    423: "Liechtenstein",

    # Africa
    20:  "Egypt",
    27:  "South Africa",
    211: "South Sudan",
    212: "Morocco",
    213: "Algeria",
    216: "Tunisia",
    218: "Libya",
    220: "Gambia",
    221: "Senegal",
    222: "Mauritania",
    223: "Mali",
    224: "Guinea",
    225: "Ivory Coast",
    226: "Burkina Faso",
    227: "Niger",
    228: "Togo",
    229: "Benin",
    230: "Mauritius",
    231: "Liberia",
    232: "Sierra Leone",
    233: "Ghana",
    234: "Nigeria",
    235: "Chad",
    236: "Central African Republic",
    237: "Cameroon",
    238: "Cape Verde",
    239: "Sao Tome and Principe",
    240: "Equatorial Guinea",
    241: "Gabon",
    242: "Republic of the Congo",
    243: "Democratic Republic of the Congo",
    244: "Angola",
    245: "Guinea-Bissau",
    246: "Diego Garcia",
    247: "Ascension Island",
    248: "Seychelles",
    249: "Sudan",
    250: "Rwanda",
    251: "Ethiopia",
    252: "Somalia",
    253: "Djibouti",
    254: "Kenya",
    255: "Tanzania",
    256: "Uganda",
    257: "Burundi",
    258: "Mozambique",
    260: "Zambia",
    261: "Madagascar",
    262: "Réunion",
    263: "Zimbabwe",
    264: "Namibia",
    265: "Malawi",
    266: "Lesotho",
    267: "Botswana",
    268: "Eswatini",
    269: "Comoros",
    290: "Saint Helena",
    291: "Eritrea",
    297: "Aruba",
    298: "Faroe Islands",
    299: "Greenland",

    # Asia
    60:  "Malaysia",
    62:  "Indonesia",
    63:  "Philippines",
    64:  "New Zealand",
    65:  "Singapore",
    66:  "Thailand",
    81:  "Japan",
    82:  "South Korea",
    84:  "Vietnam",
    86:  "China",
    90:  "Turkey",
    91:  "India",
    92:  "Pakistan",
    93:  "Afghanistan",
    94:  "Sri Lanka",
    95:  "Myanmar",
    98:  "Iran",
    850: "North Korea",
    852: "Hong Kong",
    853: "Macau",
    855: "Cambodia",
    856: "Laos",
    880: "Bangladesh",
    886: "Taiwan",
    960: "Maldives",
    961: "Lebanon",
    962: "Jordan",
    963: "Syria",
    964: "Iraq",
    965: "Kuwait",
    966: "Saudi Arabia",
    967: "Yemen",
    968: "Oman",
    970: "Palestine",
    971: "United Arab Emirates",
    972: "Israel",
    973: "Bahrain",
    974: "Qatar",
    975: "Bhutan",
    976: "Mongolia",
    977: "Nepal",
    992: "Tajikistan",
    993: "Turkmenistan",
    994: "Azerbaijan",
    995: "Georgia",
    996: "Kyrgyzstan",
    998: "Uzbekistan",

    # Southeast Asia / Pacific
    670: "Timor-Leste",
    672: "Australian External Territories",
    673: "Brunei",
    674: "Nauru",
    675: "Papua New Guinea",
    676: "Tonga",
    677: "Solomon Islands",
    678: "Vanuatu",
    679: "Fiji",
    680: "Palau",
    681: "Wallis and Futuna",
    682: "Cook Islands",
    683: "Niue",
    685: "Samoa",
    686: "Kiribati",
    687: "New Caledonia",
    688: "Tuvalu",
    689: "French Polynesia",
    690: "Tokelau",
    691: "Micronesia",
    692: "Marshall Islands",

    # South America
    54:  "Argentina",
    55:  "Brazil",
    56:  "Chile",
    57:  "Colombia",
    58:  "Venezuela",
    591: "Bolivia",
    592: "Guyana",
    593: "Ecuador",
    594: "French Guiana",
    595: "Paraguay",
    596: "Martinique",
    597: "Suriname",
    598: "Uruguay",
    599: "Curaçao",

    # Central America & Caribbean
    501: "Belize",
    502: "Guatemala",
    503: "El Salvador",
    504: "Honduras",
    505: "Nicaragua",
    506: "Costa Rica",
    507: "Panama",
    509: "Haiti",

    # Russia (covers both Europe and Asia)
    7:   "Russia",

    # International
    800: "International Freephone",
    808: "International Shared Cost",
    870: "Inmarsat",
    878: "Universal Personal Telecommunications",
    881: "Global Mobile Satellite System",
    882: "International Networks",
    883: "International Networks",
    979: "International Premium Rate",
}


# =============================================================================
# COUNTRY -> CALLING CODE
# =============================================================================
COUNTRY_TO_CALLING_CODE = {v: k for k, v in CALLING_CODE_TO_COUNTRY.items()}

# Add countries that share calling code 1 (NANP) as a special case
COUNTRY_TO_CALLING_CODE.update({
    "United States": 1,
    "Canada":        1,
})


# =============================================================================
# NANP AREA CODES (calling code +1)
# =============================================================================
# North American Numbering Plan: United States, Canada, and Caribbean
# territories share the country code +1. The area code identifies the
# specific region.

NANP_AREA_CODES = {
    # --- United States ---
    1201: "United States (New Jersey)",
    1202: "United States (Washington, D.C.)",
    1203: "United States (Connecticut)",
    1205: "United States (Alabama)",
    1206: "United States (Washington)",
    1207: "United States (Maine)",
    1208: "United States (Idaho)",
    1209: "United States (California)",
    1210: "United States (Texas)",
    1212: "United States (New York)",
    1213: "United States (California)",
    1214: "United States (Texas)",
    1215: "United States (Pennsylvania)",
    1216: "United States (Ohio)",
    1217: "United States (Illinois)",
    1218: "United States (Minnesota)",
    1219: "United States (Indiana)",
    1220: "United States (Ohio)",
    1224: "United States (Illinois)",
    1225: "United States (Louisiana)",
    1228: "United States (Mississippi)",
    1229: "United States (Georgia)",
    1231: "United States (Michigan)",
    1234: "United States (Ohio)",
    1239: "United States (Florida)",
    1240: "United States (Maryland)",
    1248: "United States (Michigan)",
    1251: "United States (Alabama)",
    1252: "United States (North Carolina)",
    1253: "United States (Washington)",
    1254: "United States (Texas)",
    1256: "United States (Alabama)",
    1260: "United States (Indiana)",
    1262: "United States (Wisconsin)",
    1267: "United States (Pennsylvania)",
    1269: "United States (Michigan)",
    1270: "United States (Kentucky)",
    1272: "United States (Pennsylvania)",
    1274: "United States (Wisconsin)",
    1276: "United States (Virginia)",
    1278: "United States (Virginia)",
    1280: "United States (Arizona)",
    1281: "United States (Texas)",
    1283: "United States (Ohio)",
    1301: "United States (Maryland)",
    1302: "United States (Delaware)",
    1303: "United States (Colorado)",
    1304: "United States (West Virginia)",
    1305: "United States (Florida)",
    1307: "United States (Wyoming)",
    1308: "United States (Nebraska)",
    1309: "United States (Illinois)",
    1310: "United States (California)",
    1312: "United States (Illinois)",
    1313: "United States (Michigan)",
    1314: "United States (Missouri)",
    1315: "United States (New York)",
    1316: "United States (Kansas)",
    1317: "United States (Indiana)",
    1318: "United States (Louisiana)",
    1319: "United States (Iowa)",
    1320: "United States (Minnesota)",
    1321: "United States (Florida)",
    1323: "United States (California)",
    1325: "United States (Texas)",
    1326: "United States (Ohio)",
    1327: "United States (Ohio)",
    1328: "United States (North Carolina)",
    1330: "United States (Ohio)",
    1331: "United States (Illinois)",
    1332: "United States (New York)",
    1334: "United States (Alabama)",
    1336: "United States (North Carolina)",
    1337: "United States (Louisiana)",
    1339: "United States (Massachusetts)",
    1341: "United States (California)",
    1346: "United States (Texas)",
    1347: "United States (New York)",
    1350: "United States (California)",
    1351: "United States (Massachusetts)",
    1352: "United States (Florida)",
    1353: "United States (Indiana)",
    1354: "United States (Texas)",
    1355: "United States (Hawaii)",
    1360: "United States (Washington)",
    1361: "United States (Texas)",
    1364: "United States (Kentucky)",
    1369: "United States (California)",
    1380: "United States (Ohio)",
    1385: "United States (Utah)",
    1386: "United States (Florida)",
    1401: "United States (Rhode Island)",
    1402: "United States (Nebraska)",
    1404: "United States (Georgia)",
    1405: "United States (Oklahoma)",
    1406: "United States (Montana)",
    1407: "United States (Florida)",
    1408: "United States (California)",
    1409: "United States (Texas)",
    1410: "United States (Maryland)",
    1412: "United States (Pennsylvania)",
    1413: "United States (Massachusetts)",
    1414: "United States (Wisconsin)",
    1415: "United States (California)",
    1417: "United States (Missouri)",
    1419: "United States (Ohio)",
    1423: "United States (Tennessee)",
    1424: "United States (California)",
    1425: "United States (Washington)",
    1430: "United States (Texas)",
    1432: "United States (Texas)",
    1434: "United States (Virginia)",
    1435: "United States (Utah)",
    1436: "United States (Ohio)",
    1440: "United States (Ohio)",
    1442: "United States (Maryland)",
    1443: "United States (Maryland)",
    1445: "United States (Pennsylvania)",
    1458: "United States (Oregon)",
    1463: "United States (Indiana)",
    1464: "United States (New York)",
    1469: "United States (Texas)",
    1470: "United States (Georgia)",
    1475: "United States (Connecticut)",
    1478: "United States (Georgia)",
    1479: "United States (Arkansas)",
    1480: "United States (Arizona)",
    1484: "United States (Pennsylvania)",
    1500: "United States (Oregon)",
    1501: "United States (Arkansas)",
    1502: "United States (Kentucky)",
    1503: "United States (Oregon)",
    1504: "United States (Louisiana)",
    1505: "United States (New Mexico)",
    1507: "United States (Minnesota)",
    1508: "United States (Massachusetts)",
    1509: "United States (Washington)",
    1510: "United States (California)",
    1512: "United States (Texas)",
    1513: "United States (Ohio)",
    1515: "United States (Iowa)",
    1516: "United States (New York)",
    1517: "United States (Michigan)",
    1518: "United States (New York)",
    1520: "United States (Arizona)",
    1530: "United States (California)",
    1531: "United States (Nebraska)",
    1534: "United States (Wisconsin)",
    1539: "United States (Oklahoma)",
    1540: "United States (Virginia)",
    1541: "United States (Oregon)",
    1551: "United States (New Jersey)",
    1559: "United States (California)",
    1562: "United States (California)",
    1563: "United States (Iowa)",
    1564: "United States (Washington)",
    1566: "United States (Wyoming)",
    1567: "United States (Ohio)",
    1570: "United States (Pennsylvania)",
    1571: "United States (Virginia)",
    1573: "United States (Missouri)",
    1574: "United States (Indiana)",
    1575: "United States (New Mexico)",
    1580: "United States (Oklahoma)",
    1585: "United States (New York)",
    1586: "United States (Michigan)",
    1600: "United States (Idaho)",
    1601: "United States (Mississippi)",
    1602: "United States (Arizona)",
    1603: "United States (New Hampshire)",
    1605: "United States (South Dakota)",
    1606: "United States (Kentucky)",
    1607: "United States (New York)",
    1608: "United States (Wisconsin)",
    1609: "United States (New Jersey)",
    1610: "United States (Pennsylvania)",
    1612: "United States (Minnesota)",
    1614: "United States (Ohio)",
    1615: "United States (Tennessee)",
    1616: "United States (Michigan)",
    1617: "United States (Massachusetts)",
    1618: "United States (Illinois)",
    1619: "United States (California)",
    1620: "United States (Kansas)",
    1623: "United States (Arizona)",
    1626: "United States (California)",
    1628: "United States (California)",
    1629: "United States (Tennessee)",
    1630: "United States (Illinois)",
    1631: "United States (New York)",
    1636: "United States (Missouri)",
    1640: "United States (New Jersey)",
    1641: "United States (Iowa)",
    1646: "United States (New York)",
    1650: "United States (California)",
    1651: "United States (Minnesota)",
    1657: "United States (California)",
    1659: "United States (Alabama)",
    1660: "United States (Missouri)",
    1661: "United States (California)",
    1662: "United States (Mississippi)",
    1663: "United States (Minnesota)",
    1667: "United States (Maryland)",
    1668: "United States (North Carolina)",
    1669: "United States (California)",
    1678: "United States (Georgia)",
    1680: "United States (New York)",
    1681: "United States (West Virginia)",
    1682: "United States (Texas)",
    1701: "United States (North Dakota)",
    1702: "United States (Nevada)",
    1703: "United States (Virginia)",
    1704: "United States (North Carolina)",
    1706: "United States (Georgia)",
    1707: "United States (California)",
    1708: "United States (Illinois)",
    1710: "United States (New York)",
    1712: "United States (Iowa)",
    1713: "United States (Texas)",
    1714: "United States (California)",
    1715: "United States (Wisconsin)",
    1716: "United States (New York)",
    1717: "United States (Pennsylvania)",
    1718: "United States (New York)",
    1719: "United States (Colorado)",
    1720: "United States (Colorado)",
    1724: "United States (Pennsylvania)",
    1725: "United States (Nevada)",
    1726: "United States (Texas)",
    1727: "United States (Florida)",
    1731: "United States (Tennessee)",
    1732: "United States (New Jersey)",
    1734: "United States (Michigan)",
    1737: "United States (Texas)",
    1740: "United States (Ohio)",
    1743: "United States (North Carolina)",
    1747: "United States (California)",
    1752: "United States (Virginia)",
    1754: "United States (Florida)",
    1757: "United States (Virginia)",
    1760: "United States (California)",
    1762: "United States (Georgia)",
    1763: "United States (Minnesota)",
    1765: "United States (Indiana)",
    1769: "United States (Mississippi)",
    1770: "United States (Georgia)",
    1772: "United States (Florida)",
    1773: "United States (Illinois)",
    1774: "United States (Massachusetts)",
    1775: "United States (Nevada)",
    1779: "United States (New York)",
    1781: "United States (Massachusetts)",
    1785: "United States (Kansas)",
    1786: "United States (Florida)",
    1801: "United States (Utah)",
    1802: "United States (Vermont)",
    1803: "United States (South Carolina)",
    1804: "United States (Virginia)",
    1805: "United States (California)",
    1806: "United States (Texas)",
    1808: "United States (Hawaii)",
    1810: "United States (Michigan)",
    1812: "United States (Indiana)",
    1813: "United States (Florida)",
    1814: "United States (Pennsylvania)",
    1815: "United States (Illinois)",
    1816: "United States (Missouri)",
    1817: "United States (Texas)",
    1818: "United States (California)",
    1820: "United States (Kansas)",
    1828: "United States (North Carolina)",
    1830: "United States (Texas)",
    1831: "United States (California)",
    1832: "United States (Texas)",
    1835: "United States (Pennsylvania)",
    1838: "United States (New York)",
    1839: "United States (Pennsylvania)",
    1840: "United States (California)",
    1843: "United States (South Carolina)",
    1845: "United States (New York)",
    1847: "United States (Illinois)",
    1848: "United States (New Jersey)",
    1850: "United States (Florida)",
    1854: "United States (South Carolina)",
    1856: "United States (New Jersey)",
    1857: "United States (Massachusetts)",
    1858: "United States (California)",
    1859: "United States (Kentucky)",
    1860: "United States (Connecticut)",
    1862: "United States (New Jersey)",
    1863: "United States (Florida)",
    1864: "United States (South Carolina)",
    1865: "United States (Tennessee)",
    1870: "United States (Arkansas)",
    1872: "United States (Georgia)",
    1875: "United States (Mississippi)",
    1878: "United States (Pennsylvania)",
    1879: "United States (New Hampshire)",
    1901: "United States (Tennessee)",
    1903: "United States (Texas)",
    1904: "United States (Florida)",
    1906: "United States (Michigan)",
    1907: "United States (Alaska)",
    1908: "United States (New Jersey)",
    1909: "United States (California)",
    1910: "United States (North Carolina)",
    1912: "United States (Georgia)",
    1913: "United States (Kansas)",
    1914: "United States (New York)",
    1915: "United States (Texas)",
    1916: "United States (California)",
    1917: "United States (New York)",
    1918: "United States (Oklahoma)",
    1919: "United States (North Carolina)",
    1920: "United States (Wisconsin)",
    1925: "United States (California)",
    1928: "United States (Arizona)",
    1929: "United States (New York)",
    1930: "United States (Indiana)",
    1931: "United States (Tennessee)",
    1935: "United States (Massachusetts)",
    1936: "United States (Texas)",
    1937: "United States (Ohio)",
    1938: "United States (Alabama)",
    1939: "United States (Massachusetts)",
    1940: "United States (Texas)",
    1941: "United States (Florida)",
    1943: "United States (Georgia)",
    1947: "United States (New York)",
    1948: "United States (Florida)",
    1949: "United States (California)",
    1951: "United States (California)",
    1952: "United States (Minnesota)",
    1953: "United States (Washington)",
    1954: "United States (Florida)",
    1956: "United States (Texas)",
    1957: "United States (Virginia)",
    1958: "United States (Florida)",
    1959: "United States (Connecticut)",
    1970: "United States (Colorado)",
    1971: "United States (California)",
    1972: "United States (Texas)",
    1973: "United States (New Jersey)",
    1974: "United States (Pennsylvania)",
    1975: "United States (Massachusetts)",
    1978: "United States (Massachusetts)",
    1979: "United States (Michigan)",
    1980: "United States (North Carolina)",
    1984: "United States (North Carolina)",
    1985: "United States (Louisiana)",
    1986: "United States (Idaho)",
    1989: "United States (Michigan)",

    # --- Canada ---
    1236: "Canada (British Columbia)",
    1249: "Canada (Ontario)",
    1250: "Canada (British Columbia)",
    1306: "Canada (Saskatchewan)",
    1343: "Canada (Ontario)",
    1365: "Canada (Ontario)",
    1367: "Canada (Quebec)",
    1403: "Canada (Alberta)",
    1416: "Canada (Ontario)",
    1418: "Canada (Quebec)",
    1431: "Canada (Manitoba)",
    1437: "Canada (Ontario)",
    1438: "Canada (Quebec)",
    1450: "Canada (British Columbia)",
    1506: "Canada (New Brunswick)",
    1514: "Canada (Quebec)",
    1519: "Canada (Ontario)",
    1579: "Canada (Quebec)",
    1581: "Canada (Quebec)",
    1587: "Canada (Alberta)",
    1604: "Canada (British Columbia)",
    1613: "Canada (Ontario)",
    1639: "Canada (Saskatchewan)",
    1647: "Canada (Ontario)",
    1672: "Canada (British Columbia)",
    1705: "Canada (Ontario)",
    1709: "Canada (Newfoundland)",
    1778: "Canada (British Columbia)",
    1780: "Canada (Alberta)",
    1782: "Canada (Nova Scotia)",
    1807: "Canada (Ontario)",
    1819: "Canada (Quebec)",
    1825: "Canada (Alberta)",
    1867: "Canada (Northwest Territories)",
    1873: "Canada (Quebec)",
    1902: "Canada (Nova Scotia)",
    1905: "Canada (Ontario)",

    # --- Caribbean territories (NANP) ---
    1242: "Bahamas",
    1246: "Barbados",
    1264: "Anguilla",
    1268: "Antigua and Barbuda",
    1284: "British Virgin Islands",
    1340: "US Virgin Islands",
    1345: "Cayman Islands",
    1441: "Bermuda",
    1473: "Grenada",
    1649: "Turks and Caicos Islands",
    1658: "Jamaica",
    1664: "Montserrat",
    1670: "Northern Mariana Islands",
    1671: "Guam",
    1684: "American Samoa",
    1721: "Sint Maarten",
    1758: "Saint Lucia",
    1767: "Dominica",
    1784: "Saint Vincent and the Grenadines",
    1787: "Puerto Rico",
    1809: "Dominican Republic",
    1829: "Dominican Republic",
    1849: "Dominican Republic",
    1868: "Trinidad and Tobago",
    1869: "Saint Kitts and Nevis",
    1876: "Jamaica",
}


# =============================================================================
# INTERNATIONAL DIAL-OUT PREFIXES
# =============================================================================
# The prefix used to place an international call from each country.
# Most countries use 00, but some (e.g. US/Canada) use 011.

INTERNATIONAL_DIAL_OUT = {
    "United States":  "011",
    "Canada":         "011",
    "Australia":      "0011",
    "Brazil":         "00",
    "China":          "00",
    "France":         "00",
    "Germany":        "00",
    "India":          "00",
    "Iran":           "00",
    "Japan":          "010",
    "Russia":         "810",
    "United Kingdom": "00",
}


__all__ = [name for name in dir() if name.isupper() and not name.startswith("_")]