# -*- coding: utf-8 -*-
"""
================================================================================
 world/iso_codes.py
================================================================================
 ISO 3166-1 country codes (alpha-2, alpha-3) and numeric codes.

 Data only.
================================================================================
"""

# =============================================================================
# COUNTRY -> ISO ALPHA-2
# =============================================================================
ISO_ALPHA2 = {
    # --- Asia ---
    "Afghanistan": "AF", "Armenia": "AM", "Azerbaijan": "AZ",
    "Bahrain": "BH", "Bangladesh": "BD", "Bhutan": "BT",
    "Brunei": "BN", "Cambodia": "KH", "China": "CN",
    "Cyprus": "CY", "Georgia": "GE", "India": "IN",
    "Indonesia": "ID", "Iran": "IR", "Iraq": "IQ",
    "Israel": "IL", "Japan": "JP", "Jordan": "JO",
    "Kazakhstan": "KZ", "Kuwait": "KW", "Kyrgyzstan": "KG",
    "Laos": "LA", "Lebanon": "LB", "Malaysia": "MY",
    "Maldives": "MV", "Mongolia": "MN", "Myanmar": "MM",
    "Nepal": "NP", "North Korea": "KP", "Oman": "OM",
    "Pakistan": "PK", "Palestine": "PS", "Philippines": "PH",
    "Qatar": "QA", "Russia": "RU", "Saudi Arabia": "SA",
    "Singapore": "SG", "South Korea": "KR", "Sri Lanka": "LK",
    "Syria": "SY", "Taiwan": "TW", "Tajikistan": "TJ",
    "Thailand": "TH", "Timor-Leste": "TL", "Turkey": "TR",
    "Turkmenistan": "TM", "United Arab Emirates": "AE",
    "Uzbekistan": "UZ", "Vietnam": "VN", "Yemen": "YE",
    "Hong Kong": "HK", "Macau": "MO",

    # --- Europe ---
    "Albania": "AL", "Andorra": "AD", "Austria": "AT",
    "Belarus": "BY", "Belgium": "BE", "Bosnia and Herzegovina": "BA",
    "Bulgaria": "BG", "Croatia": "HR", "Czech Republic": "CZ",
    "Denmark": "DK", "Estonia": "EE", "Finland": "FI",
    "France": "FR", "Germany": "DE", "Greece": "GR",
    "Hungary": "HU", "Iceland": "IS", "Ireland": "IE",
    "Italy": "IT", "Kosovo": "XK", "Latvia": "LV",
    "Liechtenstein": "LI", "Lithuania": "LT", "Luxembourg": "LU",
    "Malta": "MT", "Moldova": "MD", "Monaco": "MC",
    "Montenegro": "ME", "Netherlands": "NL", "North Macedonia": "MK",
    "Norway": "NO", "Poland": "PL", "Portugal": "PT",
    "Romania": "RO", "San Marino": "SM", "Serbia": "RS",
    "Slovakia": "SK", "Slovenia": "SI", "Spain": "ES",
    "Sweden": "SE", "Switzerland": "CH", "Ukraine": "UA",
    "United Kingdom": "GB", "Vatican City": "VA",

    # --- North America ---
    "Antigua and Barbuda": "AG", "Bahamas": "BS", "Barbados": "BB",
    "Belize": "BZ", "Canada": "CA", "Costa Rica": "CR",
    "Cuba": "CU", "Dominica": "DM", "Dominican Republic": "DO",
    "El Salvador": "SV", "Grenada": "GD", "Guatemala": "GT",
    "Haiti": "HT", "Honduras": "HN", "Jamaica": "JM",
    "Mexico": "MX", "Nicaragua": "NI", "Panama": "PA",
    "Saint Kitts and Nevis": "KN", "Saint Lucia": "LC",
    "Saint Vincent and the Grenadines": "VC",
    "Trinidad and Tobago": "TT", "United States": "US",

    # --- South America ---
    "Argentina": "AR", "Bolivia": "BO", "Brazil": "BR",
    "Chile": "CL", "Colombia": "CO", "Ecuador": "EC",
    "Guyana": "GY", "Paraguay": "PY", "Peru": "PE",
    "Suriname": "SR", "Uruguay": "UY", "Venezuela": "VE",

    # --- Africa ---
    "Algeria": "DZ", "Angola": "AO", "Benin": "BJ",
    "Botswana": "BW", "Burkina Faso": "BF", "Burundi": "BI",
    "Cameroon": "CM", "Cape Verde": "CV",
    "Central African Republic": "CF", "Chad": "TD",
    "Comoros": "KM", "Democratic Republic of the Congo": "CD",
    "Republic of the Congo": "CG", "Djibouti": "DJ",
    "Egypt": "EG", "Equatorial Guinea": "GQ", "Eritrea": "ER",
    "Eswatini": "SZ", "Ethiopia": "ET", "Gabon": "GA",
    "Gambia": "GM", "Ghana": "GH", "Guinea": "GN",
    "Guinea-Bissau": "GW", "Ivory Coast": "CI", "Kenya": "KE",
    "Lesotho": "LS", "Liberia": "LR", "Libya": "LY",
    "Madagascar": "MG", "Malawi": "MW", "Mali": "ML",
    "Mauritania": "MR", "Mauritius": "MU", "Morocco": "MA",
    "Mozambique": "MZ", "Namibia": "NA", "Niger": "NE",
    "Nigeria": "NG", "Rwanda": "RW", "Sao Tome and Principe": "ST",
    "Senegal": "SN", "Seychelles": "SC", "Sierra Leone": "SL",
    "Somalia": "SO", "South Africa": "ZA", "South Sudan": "SS",
    "Sudan": "SD", "Tanzania": "TZ", "Togo": "TG",
    "Tunisia": "TN", "Uganda": "UG", "Zambia": "ZM",
    "Zimbabwe": "ZW", "Réunion": "RE", "Saint Helena": "SH",

    # --- Oceania ---
    "Australia": "AU", "Fiji": "FJ", "Kiribati": "KI",
    "Marshall Islands": "MH", "Micronesia": "FM", "Nauru": "NR",
    "New Zealand": "NZ", "Palau": "PW", "Papua New Guinea": "PG",
    "Samoa": "WS", "Solomon Islands": "SB", "Tonga": "TO",
    "Tuvalu": "TV", "Vanuatu": "VU",

    # --- Territories ---
    "American Samoa": "AS", "Anguilla": "AI", "Aruba": "AW",
    "Bermuda": "BM", "British Virgin Islands": "VG",
    "Cayman Islands": "KY", "Cook Islands": "CK",
    "Curaçao": "CW", "Falkland Islands": "FK",
    "Faroe Islands": "FO", "French Guiana": "GF",
    "French Polynesia": "PF", "Gibraltar": "GI",
    "Greenland": "GL", "Guadeloupe": "GP", "Guam": "GU",
    "Martinique": "MQ", "Montserrat": "MS",
    "New Caledonia": "NC", "Niue": "NU",
    "Northern Mariana Islands": "MP", "Puerto Rico": "PR",
    "Sint Maarten": "SX", "Turks and Caicos Islands": "TC",
    "US Virgin Islands": "VI", "Wallis and Futuna": "WF",
}

# Reverse: ISO2 -> country
ISO2_TO_COUNTRY = {v: k for k, v in ISO_ALPHA2.items()}


# =============================================================================
# COUNTRY -> ISO ALPHA-3
# =============================================================================
ISO_ALPHA3 = {
    "Afghanistan": "AFG", "Albania": "ALB", "Algeria": "DZA",
    "Andorra": "AND", "Angola": "AGO", "Antigua and Barbuda": "ATG",
    "Argentina": "ARG", "Armenia": "ARM", "Australia": "AUS",
    "Austria": "AUT", "Azerbaijan": "AZE", "Bahamas": "BHS",
    "Bahrain": "BHR", "Bangladesh": "BGD", "Barbados": "BRB",
    "Belarus": "BLR", "Belgium": "BEL", "Belize": "BLZ",
    "Benin": "BEN", "Bhutan": "BTN", "Bolivia": "BOL",
    "Bosnia and Herzegovina": "BIH", "Botswana": "BWA",
    "Brazil": "BRA", "Brunei": "BRN", "Bulgaria": "BGR",
    "Burkina Faso": "BFA", "Burundi": "BDI", "Cambodia": "KHM",
    "Cameroon": "CMR", "Canada": "CAN", "Cape Verde": "CPV",
    "Central African Republic": "CAF", "Chad": "TCD",
    "Chile": "CHL", "China": "CHN", "Colombia": "COL",
    "Comoros": "COM", "Republic of the Congo": "COG",
    "Democratic Republic of the Congo": "COD",
    "Costa Rica": "CRI", "Croatia": "HRV", "Cuba": "CUB",
    "Cyprus": "CYP", "Czech Republic": "CZE", "Denmark": "DNK",
    "Djibouti": "DJI", "Dominica": "DMA",
    "Dominican Republic": "DOM", "Ecuador": "ECU",
    "Egypt": "EGY", "El Salvador": "SLV",
    "Equatorial Guinea": "GNQ", "Eritrea": "ERI",
    "Estonia": "EST", "Eswatini": "SWZ", "Ethiopia": "ETH",
    "Fiji": "FJI", "Finland": "FIN", "France": "FRA",
    "Gabon": "GAB", "Gambia": "GMB", "Georgia": "GEO",
    "Germany": "DEU", "Ghana": "GHA", "Greece": "GRC",
    "Grenada": "GRD", "Guatemala": "GTM", "Guinea": "GIN",
    "Guinea-Bissau": "GNB", "Guyana": "GUY", "Haiti": "HTI",
    "Honduras": "HND", "Hungary": "HUN", "Iceland": "ISL",
    "India": "IND", "Indonesia": "IDN", "Iran": "IRN",
    "Iraq": "IRQ", "Ireland": "IRL", "Israel": "ISR",
    "Italy": "ITA", "Ivory Coast": "CIV", "Jamaica": "JAM",
    "Japan": "JPN", "Jordan": "JOR", "Kazakhstan": "KAZ",
    "Kenya": "KEN", "Kiribati": "KIR", "Kosovo": "XKX",
    "Kuwait": "KWT", "Kyrgyzstan": "KGZ", "Laos": "LAO",
    "Latvia": "LVA", "Lebanon": "LBN", "Lesotho": "LSO",
    "Liberia": "LBR", "Libya": "LBY", "Liechtenstein": "LIE",
    "Lithuania": "LTU", "Luxembourg": "LUX", "Madagascar": "MDG",
    "Malawi": "MWI", "Malaysia": "MYS", "Maldives": "MDV",
    "Mali": "MLI", "Malta": "MLT", "Marshall Islands": "MHL",
    "Mauritania": "MRT", "Mauritius": "MUS", "Mexico": "MEX",
    "Micronesia": "FSM", "Moldova": "MDA", "Monaco": "MCO",
    "Mongolia": "MNG", "Montenegro": "MNE", "Morocco": "MAR",
    "Mozambique": "MOZ", "Myanmar": "MMR", "Namibia": "NAM",
    "Nauru": "NRU", "Nepal": "NPL", "Netherlands": "NLD",
    "New Zealand": "NZL", "Nicaragua": "NIC", "Niger": "NER",
    "Nigeria": "NGA", "North Korea": "PRK",
    "North Macedonia": "MKD", "Norway": "NOR", "Oman": "OMN",
    "Pakistan": "PAK", "Palau": "PLW", "Palestine": "PSE",
    "Panama": "PAN", "Papua New Guinea": "PNG", "Paraguay": "PRY",
    "Peru": "PER", "Philippines": "PHL", "Poland": "POL",
    "Portugal": "PRT", "Qatar": "QAT", "Romania": "ROU",
    "Russia": "RUS", "Rwanda": "RWA",
    "Saint Kitts and Nevis": "KNA", "Saint Lucia": "LCA",
    "Saint Vincent and the Grenadines": "VCT", "Samoa": "WSM",
    "San Marino": "SMR", "Sao Tome and Principe": "STP",
    "Saudi Arabia": "SAU", "Senegal": "SEN", "Serbia": "SRB",
    "Seychelles": "SYC", "Sierra Leone": "SLE",
    "Singapore": "SGP", "Slovakia": "SVK", "Slovenia": "SVN",
    "Solomon Islands": "SLB", "Somalia": "SOM",
    "South Africa": "ZAF", "South Korea": "KOR",
    "South Sudan": "SSD", "Spain": "ESP", "Sri Lanka": "LKA",
    "Sudan": "SDN", "Suriname": "SUR", "Sweden": "SWE",
    "Switzerland": "CHE", "Syria": "SYR", "Taiwan": "TWN",
    "Tajikistan": "TJK", "Tanzania": "TZA", "Thailand": "THA",
    "Timor-Leste": "TLS", "Togo": "TGO", "Tonga": "TON",
    "Trinidad and Tobago": "TTO", "Tunisia": "TUN",
    "Turkey": "TUR", "Turkmenistan": "TKM", "Tuvalu": "TUV",
    "Uganda": "UGA", "Ukraine": "UKR",
    "United Arab Emirates": "ARE", "United Kingdom": "GBR",
    "United States": "USA", "Uruguay": "URY", "Uzbekistan": "UZB",
    "Vanuatu": "VUT", "Vatican City": "VAT", "Venezuela": "VEN",
    "Vietnam": "VNM", "Yemen": "YEM", "Zambia": "ZMB",
    "Zimbabwe": "ZWE",
}

ISO3_TO_COUNTRY = {v: k for k, v in ISO_ALPHA3.items()}


# =============================================================================
# COUNTRY -> ISO 3166-1 NUMERIC
# =============================================================================
ISO_NUMERIC = {
    "Afghanistan": "004", "Albania": "008", "Algeria": "012",
    "Andorra": "020", "Angola": "024", "Antigua and Barbuda": "028",
    "Argentina": "032", "Armenia": "051", "Australia": "036",
    "Austria": "040", "Azerbaijan": "031", "Bahamas": "044",
    "Bahrain": "048", "Bangladesh": "050", "Barbados": "052",
    "Belarus": "112", "Belgium": "056", "Belize": "084",
    "Benin": "204", "Bhutan": "064", "Bolivia": "068",
    "Bosnia and Herzegovina": "070", "Botswana": "072",
    "Brazil": "076", "Brunei": "096", "Bulgaria": "100",
    "Burkina Faso": "854", "Burundi": "108", "Cambodia": "116",
    "Cameroon": "120", "Canada": "124", "Cape Verde": "132",
    "Central African Republic": "140", "Chad": "148",
    "Chile": "152", "China": "156", "Colombia": "170",
    "Comoros": "174", "Republic of the Congo": "178",
    "Democratic Republic of the Congo": "180",
    "Costa Rica": "188", "Croatia": "191", "Cuba": "192",
    "Cyprus": "196", "Czech Republic": "203", "Denmark": "208",
    "Djibouti": "262", "Dominica": "212",
    "Dominican Republic": "214", "Ecuador": "218",
    "Egypt": "818", "El Salvador": "222",
    "Equatorial Guinea": "226", "Eritrea": "232",
    "Estonia": "233", "Eswatini": "748", "Ethiopia": "231",
    "Fiji": "242", "Finland": "246", "France": "250",
    "Gabon": "266", "Gambia": "270", "Georgia": "268",
    "Germany": "276", "Ghana": "288", "Greece": "300",
    "Grenada": "308", "Guatemala": "320", "Guinea": "324",
    "Guinea-Bissau": "624", "Guyana": "328", "Haiti": "332",
    "Honduras": "340", "Hungary": "348", "Iceland": "352",
    "India": "356", "Indonesia": "360", "Iran": "364",
    "Iraq": "368", "Ireland": "372", "Israel": "376",
    "Italy": "380", "Ivory Coast": "384", "Jamaica": "388",
    "Japan": "392", "Jordan": "400", "Kazakhstan": "398",
    "Kenya": "404", "Kiribati": "296", "Kosovo": "XKX",
    "Kuwait": "414", "Kyrgyzstan": "417", "Laos": "418",
    "Latvia": "428", "Lebanon": "422", "Lesotho": "426",
    "Liberia": "430", "Libya": "434", "Liechtenstein": "438",
    "Lithuania": "440", "Luxembourg": "442", "Madagascar": "450",
    "Malawi": "454", "Malaysia": "458", "Maldives": "462",
    "Mali": "466", "Malta": "470", "Marshall Islands": "584",
    "Mauritania": "478", "Mauritius": "480", "Mexico": "484",
    "Micronesia": "583", "Moldova": "498", "Monaco": "492",
    "Mongolia": "496", "Montenegro": "499", "Morocco": "504",
    "Mozambique": "508", "Myanmar": "104", "Namibia": "516",
    "Nauru": "520", "Nepal": "524", "Netherlands": "528",
    "New Zealand": "554", "Nicaragua": "558", "Niger": "562",
    "Nigeria": "566", "North Korea": "408",
    "North Macedonia": "807", "Norway": "578", "Oman": "512",
    "Pakistan": "586", "Palau": "585", "Palestine": "275",
    "Panama": "591", "Papua New Guinea": "598", "Paraguay": "600",
    "Peru": "604", "Philippines": "608", "Poland": "616",
    "Portugal": "620", "Qatar": "634", "Romania": "642",
    "Russia": "643", "Rwanda": "646",
    "Saint Kitts and Nevis": "659", "Saint Lucia": "662",
    "Saint Vincent and the Grenadines": "670", "Samoa": "882",
    "San Marino": "674", "Sao Tome and Principe": "678",
    "Saudi Arabia": "682", "Senegal": "686", "Serbia": "688",
    "Seychelles": "690", "Sierra Leone": "694",
    "Singapore": "702", "Slovakia": "703", "Slovenia": "705",
    "Solomon Islands": "090", "Somalia": "706",
    "South Africa": "710", "South Korea": "410",
    "South Sudan": "728", "Spain": "724", "Sri Lanka": "144",
    "Sudan": "729", "Suriname": "740", "Sweden": "752",
    "Switzerland": "756", "Syria": "760", "Taiwan": "158",
    "Tajikistan": "762", "Tanzania": "834", "Thailand": "764",
    "Timor-Leste": "626", "Togo": "768", "Tonga": "776",
    "Trinidad and Tobago": "780", "Tunisia": "788",
    "Turkey": "792", "Turkmenistan": "795", "Tuvalu": "798",
    "Uganda": "800", "Ukraine": "804",
    "United Arab Emirates": "784", "United Kingdom": "826",
    "United States": "840", "Uruguay": "858", "Uzbekistan": "860",
    "Vanuatu": "548", "Vatican City": "336", "Venezuela": "862",
    "Vietnam": "704", "Yemen": "887", "Zambia": "894",
    "Zimbabwe": "716",
}


__all__ = [name for name in dir() if name.isupper() and not name.startswith("_")]