# -*- coding: utf-8 -*-
"""Language family groupings."""

from .alphabets.latin import (
    GERMAN_LOWERCASE, GERMAN_UPPERCASE,
    DUTCH_LOWERCASE, DUTCH_UPPERCASE,
    SWEDISH_LOWERCASE, SWEDISH_UPPERCASE,
    NORWEGIAN_LOWERCASE, NORWEGIAN_UPPERCASE,
    DANISH_LOWERCASE, DANISH_UPPERCASE,
    ICELANDIC_LOWERCASE, ICELANDIC_UPPERCASE,
    LUXEMBOURGISH_LOWERCASE, LUXEMBOURGISH_UPPERCASE,
    FRENCH_LOWERCASE, FRENCH_UPPERCASE,
    SPANISH_LOWERCASE, SPANISH_UPPERCASE,
    ITALIAN_LOWERCASE, ITALIAN_UPPERCASE,
    PORTUGUESE_LOWERCASE, PORTUGUESE_UPPERCASE,
    ROMANIAN_LOWERCASE, ROMANIAN_UPPERCASE,
    CATALAN_LOWERCASE, CATALAN_UPPERCASE,
    GALICIAN_LOWERCASE, GALICIAN_UPPERCASE,
    POLISH_LOWERCASE, POLISH_UPPERCASE,
    CZECH_LOWERCASE, CZECH_UPPERCASE,
    SLOVAK_LOWERCASE, SLOVAK_UPPERCASE,
    CROATIAN_LOWERCASE, CROATIAN_UPPERCASE,
    SLOVENE_LOWERCASE, SLOVENE_UPPERCASE,
    BOSNIAN_LOWERCASE, BOSNIAN_UPPERCASE,
    SERBIAN_LATIN_LOWERCASE, SERBIAN_LATIN_UPPERCASE,
    MONTENEGRIN_LATIN_LOWERCASE, MONTENEGRIN_LATIN_UPPERCASE,
    TURKISH_LOWERCASE, TURKISH_UPPERCASE,
    AZERBAIJANI_LOWERCASE, AZERBAIJANI_UPPERCASE,
    TURKMEN_LOWERCASE, TURKMEN_UPPERCASE,
    CRIMEAN_TATAR_LOWERCASE, CRIMEAN_TATAR_UPPERCASE,
)
from .alphabets.cyrillic import (
    RUSSIAN_LOWERCASE, RUSSIAN_UPPERCASE,
    UKRAINIAN_LOWERCASE, UKRAINIAN_UPPERCASE,
    BULGARIAN_LOWERCASE, BULGARIAN_UPPERCASE,
    SERBIAN_CYRILLIC_LOWERCASE, SERBIAN_CYRILLIC_UPPERCASE,
    MACEDONIAN_CYRILLIC_LOWERCASE, MACEDONIAN_CYRILLIC_UPPERCASE,
    BELARUSIAN_LOWERCASE, BELARUSIAN_UPPERCASE,
)


def _dedup(*strings):
    return "".join(dict.fromkeys("".join(strings)))


GERMANIC_LANGUAGES_CHARS = _dedup(
    GERMAN_LOWERCASE, GERMAN_UPPERCASE,
    DUTCH_LOWERCASE, DUTCH_UPPERCASE,
    SWEDISH_LOWERCASE, SWEDISH_UPPERCASE,
    NORWEGIAN_LOWERCASE, NORWEGIAN_UPPERCASE,
    DANISH_LOWERCASE, DANISH_UPPERCASE,
    ICELANDIC_LOWERCASE, ICELANDIC_UPPERCASE,
    LUXEMBOURGISH_LOWERCASE, LUXEMBOURGISH_UPPERCASE,
)

ROMANCE_LANGUAGES_CHARS = _dedup(
    FRENCH_LOWERCASE, FRENCH_UPPERCASE,
    SPANISH_LOWERCASE, SPANISH_UPPERCASE,
    ITALIAN_LOWERCASE, ITALIAN_UPPERCASE,
    PORTUGUESE_LOWERCASE, PORTUGUESE_UPPERCASE,
    ROMANIAN_LOWERCASE, ROMANIAN_UPPERCASE,
    CATALAN_LOWERCASE, CATALAN_UPPERCASE,
    GALICIAN_LOWERCASE, GALICIAN_UPPERCASE,
)

SLAVIC_LATIN_CHARS = _dedup(
    POLISH_LOWERCASE, POLISH_UPPERCASE,
    CZECH_LOWERCASE, CZECH_UPPERCASE,
    SLOVAK_LOWERCASE, SLOVAK_UPPERCASE,
    CROATIAN_LOWERCASE, CROATIAN_UPPERCASE,
    SLOVENE_LOWERCASE, SLOVENE_UPPERCASE,
    BOSNIAN_LOWERCASE, BOSNIAN_UPPERCASE,
    SERBIAN_LATIN_LOWERCASE, SERBIAN_LATIN_UPPERCASE,
    MONTENEGRIN_LATIN_LOWERCASE, MONTENEGRIN_LATIN_UPPERCASE,
)

SLAVIC_CYRILLIC_CHARS = _dedup(
    RUSSIAN_LOWERCASE, RUSSIAN_UPPERCASE,
    UKRAINIAN_LOWERCASE, UKRAINIAN_UPPERCASE,
    BULGARIAN_LOWERCASE, BULGARIAN_UPPERCASE,
    SERBIAN_CYRILLIC_LOWERCASE, SERBIAN_CYRILLIC_UPPERCASE,
    MACEDONIAN_CYRILLIC_LOWERCASE, MACEDONIAN_CYRILLIC_UPPERCASE,
    BELARUSIAN_LOWERCASE, BELARUSIAN_UPPERCASE,
)

TURKIC_LANGUAGES_CHARS = _dedup(
    TURKISH_LOWERCASE, TURKISH_UPPERCASE,
    AZERBAIJANI_LOWERCASE, AZERBAIJANI_UPPERCASE,
    TURKMEN_LOWERCASE, TURKMEN_UPPERCASE,
    CRIMEAN_TATAR_LOWERCASE, CRIMEAN_TATAR_UPPERCASE,
)


__all__ = [name for name in dir() if name.isupper() and not name.startswith("_")]