# -*- coding: utf-8 -*-
"""Combined PRINTABLE_* sets for common script groupings."""

from .whitespace import PUNCTUATION, PUNCTUATION_ASCII
from .digits import (
    DECIMAL_DIGITS, PERSIAN_DIGITS, DEVANAGARI_DIGITS, BENGALI_DIGITS,
    THAI_DIGITS, TAMIL_DIGITS, TELUGU_DIGITS, KANNADA_DIGITS,
    MALAYALAM_DIGITS, GURMUKHI_DIGITS, GUJARATI_DIGITS, ORIYA_DIGITS,
    TIBETAN_DIGITS, MYANMAR_DIGITS, KHMER_DIGITS, LAO_DIGITS,
    MONGOLIAN_DIGITS,
)
from .alphabets.latin import (
    ASCII_LETTERS, ASCII_LOWERCASE, ASCII_UPPERCASE, ALL_LATIN_LETTERS,
    GERMAN_LOWERCASE, GERMAN_UPPERCASE,
    FRENCH_LOWERCASE, FRENCH_UPPERCASE,
    SPANISH_LOWERCASE, SPANISH_UPPERCASE,
    ITALIAN_LOWERCASE, ITALIAN_UPPERCASE,
    PORTUGUESE_LOWERCASE, PORTUGUESE_UPPERCASE,
    DUTCH_LOWERCASE, DUTCH_UPPERCASE,
    POLISH_LOWERCASE, POLISH_UPPERCASE,
    CZECH_LOWERCASE, CZECH_UPPERCASE,
    TURKISH_LOWERCASE, TURKISH_UPPERCASE,
    VIETNAMESE_LOWERCASE, VIETNAMESE_UPPERCASE,
)
from .alphabets.cyrillic import (
    ALL_CYRILLIC, RUSSIAN_LOWERCASE, RUSSIAN_UPPERCASE,
    UKRAINIAN_LOWERCASE, UKRAINIAN_UPPERCASE,
    MONGOLIAN_CYRILLIC_LOWERCASE, MONGOLIAN_CYRILLIC_UPPERCASE,
)
from .alphabets.arabic import (
    ALL_ARABIC_SCRIPTS, ARABIC_ALL_FORMS, PERSIAN_FULL, URDU_LETTERS,
    PERSIAN_HARAKAT, PERSIAN_PUNCTUATION, ARABIC_DIACRITICS,
)
from .alphabets.south_asian import (
    ALL_SOUTH_ASIAN, DEVANAGARI_LETTERS, BENGALI_LETTERS,
    GURMUKHI_LETTERS, GUJARATI_LETTERS, TAMIL_LETTERS,
    TELUGU_LETTERS, KANNADA_LETTERS, MALAYALAM_LETTERS, SINHALA_LETTERS,
)
from .alphabets.southeast_asian import (
    THAI_LETTERS, LAO_LETTERS, KHMER_LETTERS, MYANMAR_LETTERS,
)
from .alphabets.east_asian import (
    CHINESE_COMMON, HIRAGANA, KATAKANA, HANGUL_LETTERS,
)
from .alphabets.other_scripts import (
    GREEK_LETTERS, HEBREW_FULL, ARMENIAN_LETTERS, GEORGIAN_LETTERS,
    AMHARIC_LETTERS, TIBETAN_LETTERS, CHEROKEE_LETTERS,
)


# ---------------------------------------------------------------------------
# General
# ---------------------------------------------------------------------------
PRINTABLE_ASCII = ASCII_LETTERS + PUNCTUATION_ASCII + DECIMAL_DIGITS
PRINTABLE_LATIN = ALL_LATIN_LETTERS + PUNCTUATION + DECIMAL_DIGITS
PRINTABLE_CYRILLIC = ALL_CYRILLIC + PUNCTUATION + DECIMAL_DIGITS
PRINTABLE_ARABIC = (
    ALL_ARABIC_SCRIPTS + PUNCTUATION + PERSIAN_DIGITS
    + ARABIC_DIACRITICS + PERSIAN_HARAKAT + PERSIAN_PUNCTUATION
)
PRINTABLE_SOUTH_ASIAN = (
    ALL_SOUTH_ASIAN + PUNCTUATION + DECIMAL_DIGITS
    + DEVANAGARI_DIGITS + BENGALI_DIGITS + TAMIL_DIGITS
    + TELUGU_DIGITS + KANNADA_DIGITS + MALAYALAM_DIGITS
    + GURMUKHI_DIGITS + GUJARATI_DIGITS + ORIYA_DIGITS
)
PRINTABLE_EAST_ASIAN = (
    CHINESE_COMMON + HIRAGANA + KATAKANA + HANGUL_LETTERS
    + PUNCTUATION + DECIMAL_DIGITS
)

PRINTABLE_GREEK = GREEK_LETTERS + PUNCTUATION + DECIMAL_DIGITS
PRINTABLE_HEBREW = HEBREW_FULL + PUNCTUATION + DECIMAL_DIGITS
PRINTABLE_ARMENIAN = ARMENIAN_LETTERS + PUNCTUATION + DECIMAL_DIGITS
PRINTABLE_GEORGIAN = GEORGIAN_LETTERS + PUNCTUATION + DECIMAL_DIGITS

PRINTABLE_THAI = THAI_LETTERS + PUNCTUATION + THAI_DIGITS
PRINTABLE_LAO = LAO_LETTERS + PUNCTUATION + LAO_DIGITS
PRINTABLE_KHMER = KHMER_LETTERS + PUNCTUATION + KHMER_DIGITS
PRINTABLE_MYANMAR = MYANMAR_LETTERS + PUNCTUATION + MYANMAR_DIGITS
PRINTABLE_TIBETAN = TIBETAN_LETTERS + PUNCTUATION + TIBETAN_DIGITS
PRINTABLE_MONGOLIAN = (
    MONGOLIAN_CYRILLIC_LOWERCASE + MONGOLIAN_CYRILLIC_UPPERCASE
    + PUNCTUATION + MONGOLIAN_DIGITS
)
PRINTABLE_CHEROKEE = CHEROKEE_LETTERS + PUNCTUATION + DECIMAL_DIGITS
PRINTABLE_ETHIOPIC = AMHARIC_LETTERS + PUNCTUATION + DECIMAL_DIGITS


# ---------------------------------------------------------------------------
# Language-specific (letters + punctuation + digits + local currency/extra)
# ---------------------------------------------------------------------------
PRINTABLE_GERMAN = GERMAN_LOWERCASE + GERMAN_UPPERCASE + PUNCTUATION + DECIMAL_DIGITS + "€"
PRINTABLE_FRENCH = FRENCH_LOWERCASE + FRENCH_UPPERCASE + PUNCTUATION + DECIMAL_DIGITS + "€"
PRINTABLE_SPANISH = SPANISH_LOWERCASE + SPANISH_UPPERCASE + PUNCTUATION + DECIMAL_DIGITS + "€¿¡"
PRINTABLE_ITALIAN = ITALIAN_LOWERCASE + ITALIAN_UPPERCASE + PUNCTUATION + DECIMAL_DIGITS + "€"
PRINTABLE_PORTUGUESE = PORTUGUESE_LOWERCASE + PORTUGUESE_UPPERCASE + PUNCTUATION + DECIMAL_DIGITS + "€"
PRINTABLE_DUTCH = DUTCH_LOWERCASE + DUTCH_UPPERCASE + PUNCTUATION + DECIMAL_DIGITS + "€"
PRINTABLE_POLISH = POLISH_LOWERCASE + POLISH_UPPERCASE + PUNCTUATION + DECIMAL_DIGITS + "zł"
PRINTABLE_CZECH = CZECH_LOWERCASE + CZECH_UPPERCASE + PUNCTUATION + DECIMAL_DIGITS + "Kč"
PRINTABLE_TURKISH = TURKISH_LOWERCASE + TURKISH_UPPERCASE + PUNCTUATION + DECIMAL_DIGITS + "₺"
PRINTABLE_VIETNAMESE = VIETNAMESE_LOWERCASE + VIETNAMESE_UPPERCASE + PUNCTUATION + DECIMAL_DIGITS + "₫"
PRINTABLE_RUSSIAN = RUSSIAN_LOWERCASE + RUSSIAN_UPPERCASE + PUNCTUATION + DECIMAL_DIGITS + "₽"
PRINTABLE_UKRAINIAN = UKRAINIAN_LOWERCASE + UKRAINIAN_UPPERCASE + PUNCTUATION + DECIMAL_DIGITS + "₴"
PRINTABLE_PERSIAN = PERSIAN_FULL + PUNCTUATION + PERSIAN_DIGITS + PERSIAN_HARAKAT + PERSIAN_PUNCTUATION + "﷼"
PRINTABLE_URDU = URDU_LETTERS + PUNCTUATION + PERSIAN_DIGITS + PERSIAN_HARAKAT + PERSIAN_PUNCTUATION + "₨"
PRINTABLE_HINDI = DEVANAGARI_LETTERS + PUNCTUATION + DEVANAGARI_DIGITS + "₹"
PRINTABLE_BENGALI = BENGALI_LETTERS + PUNCTUATION + BENGALI_DIGITS + "৳"
PRINTABLE_PUNJABI = GURMUKHI_LETTERS + PUNCTUATION + GURMUKHI_DIGITS + "₹"
PRINTABLE_GUJARATI = GUJARATI_LETTERS + PUNCTUATION + GUJARATI_DIGITS + "₹"
PRINTABLE_TAMIL = TAMIL_LETTERS + PUNCTUATION + TAMIL_DIGITS + "₹"
PRINTABLE_TELUGU = TELUGU_LETTERS + PUNCTUATION + TELUGU_DIGITS + "₹"
PRINTABLE_KANNADA = KANNADA_LETTERS + PUNCTUATION + KANNADA_DIGITS + "₹"
PRINTABLE_MALAYALAM = MALAYALAM_LETTERS + PUNCTUATION + MALAYALAM_DIGITS + "₹"
PRINTABLE_JAPANESE = HIRAGANA + KATAKANA + PUNCTUATION + DECIMAL_DIGITS + "¥"
PRINTABLE_CHINESE = CHINESE_COMMON + PUNCTUATION + DECIMAL_DIGITS + "¥"
PRINTABLE_KOREAN = HANGUL_LETTERS + PUNCTUATION + DECIMAL_DIGITS + "₩"
PRINTABLE_SINHALA = SINHALA_LETTERS + PUNCTUATION + DECIMAL_DIGITS


__all__ = [name for name in dir() if name.isupper() and not name.startswith("_")]